version: 2
updates:
  - package-ecosystem: "npm"
    # Files stored in `app` directory
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "package.json"
        update-types:
          - version-update:semver:^